src/main/java/com/psybergate/finance/domain/PropertyBond.java
package com.psybergate.finance.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.psybergate.finance.interfaces.ForecastEntry;
import com.psybergate.finance.util.PropertyBondCalculatorUtil;

public class PropertyBond {

	private int term;

	private double interestRate;

	private Money principal;

	private List<ForecastEntry> forecast = new ArrayList<>();

	private Map<Integer, Event> events = new HashMap<>();

	private boolean paidUp;

	public boolean isPaidUp() {
		return paidUp;
	}

	private void setPaidUp(boolean paidUp) {
		this.paidUp = paidUp;
	}

	public PropertyBond(int term, double interestRate, Money principal, Map<Integer, Event> events) {
		setPrincipal(principal);
		setTerm(term);
		setInterestRate(interestRate);
		setEvents(events);
	}

	public Money getMonthlyRepayment() {
		return PropertyBondCalculatorUtil.getMonthlyRepayment(interestRate, term, principal);
	}

	public Money getTransferFees() {
		return getConveyanceFees().add(getTransferDutyFees()).add(getConveyanceVatFees());
	}

	public Money getConveyanceFees() {
		return PropertyBondCalculatorUtil.getConveyanceFees(principal);
	}

	public Money getTransferDutyFees() {
		return PropertyBondCalculatorUtil.getTransferDutyFees(principal);
	}

	public Money getConveyanceVatFees() {
		return PropertyBondCalculatorUtil.getConveyanceVatFees(principal);
	}

	public List<ForecastEntry> getForecast() {
		return forecast;
	}

	public int getTerm() {
		return term;
	}

	public void setTerm(int term) {
		this.term = term;
	}

	public double getInterestRate() {
		return interestRate;
	}

	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}

	public Money getPrincipal() {
		return principal;
	}

	public void setPrincipal(Money openingBalance) {
		this.principal = openingBalance;
	}

	public Map<Integer, Event> getEvents() {
		return events;
	}

	public void setEvents(Map<Integer, Event> events) {
		this.events = events;
		generateEntries();
	}

	private void setForecast(List<ForecastEntry> forecast) {
		this.forecast = forecast;
	}

	public Money getClosingBalance() {
		return forecast.get(forecast.size() - 1).getClosingBalance();
	}

	public Money getTotalInterest() {
		Money totalRepayment = getTotalRepayment();
		return totalRepayment.subtract(principal);
	}

	public Money getTotalRepayment() {
		Money totalRepayment = new Money();
		for (ForecastEntry forecastEntry : forecast) {
			Money totalRepaymentForMonth = forecastEntry.getMonthlyAmount().add(forecastEntry.getAmount());
			totalRepayment = totalRepayment.add(totalRepaymentForMonth);
		}
		return totalRepayment;
	}

	private void addForecastEntry(ForecastEntry entry) {
		forecast.add(entry);
	}

	public void generateEntries() {
		setForecast(new ArrayList<>());
		ForecastEntry entry = new PropertyForecastEntry(1, interestRate, principal, getMonthlyRepayment(), new Money());
		applyEvents(entry);
		addForecastEntry(entry);
		for (int month = 2; month <= getTerm() && !paidUp; month++) {
			ForecastEntry prevEntry = getForecast().get(month - 2);
			entry = prevEntry.generateNextEntry();
			applyEvents(entry);
			paidUp = entry.getClosingBalance().getAmount().doubleValue() <= 0;
			addForecastEntry(entry);
		}
		clearBalance(entry);
	}

	private void clearBalance(ForecastEntry entry) {
		Money correction = entry.getMonthlyAmount().add(entry.getClosingBalance());
		entry.setMonthlyAmount(correction);
		setPaidUp(true);
	}

	public Integer getMonthPaidUp() {
		if (isPaidUp()) {
			return forecast.size();
		}
		return null;
	}

	private void applyEvents(ForecastEntry entry) {
		Event event = getEventForMonth(entry.getMonth());
		if (event != null) {
			Money newMonthlyRepayment =
					PropertyBondCalculatorUtil.getNewMonthlyRepayment(entry, event, term - entry.getMonth() + 1);
			Money currentMonthlyRepayment = entry.getMonthlyAmount();
			if (event.monthlyAmountChanged()) {
				currentMonthlyRepayment = event.getMonthlyAmount();
			}
			if (currentMonthlyRepayment.compareTo(newMonthlyRepayment) < 0) {
				event.setMonthlyAmount(newMonthlyRepayment);
			}
			entry.applyEvent(event);
		}
	}

	private Event getEventForMonth(int month) {
		return getEvents().get(month);
	}

	public void addEvent(Event event) {
		events.put(event.getMonth(), event);
		generateEntries();
	}
}

src/main/java/com/psybergate/finance/model/EventModel.java
package com.psybergate.finance.model;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import com.psybergate.finance.domain.Event;
import com.psybergate.finance.domain.Money;

@RequestScoped
@Named
public class EventModel {

	public static final String[] TRANSACTION_OPTIONS = { "Deposit", "Withdraw" };

	private Integer month;

	private Double interestRate;

	private Money monthlyAmount;

	private Money amount;

	private String transactionType;

	public EventModel() {
	}

	public Event getEvent() {
		Event event = new Event(month, interestRate, amount, monthlyAmount);
		if (amount != null && transactionType != null && transactionType.equalsIgnoreCase("withdraw")) {
			event.setAmount(new Money(amount.getAmount().negate()));
		}
		return event;
	}

	public Integer getMonth() {
		return month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Double getInterestRate() {
		return interestRate;
	}

	public void setInterestRate(Double interestRate) {
		this.interestRate = interestRate;
	}

	public Money getMonthlyAmount() {
		return monthlyAmount;
	}

	public void setMonthlyAmount(Money monthlyAmount) {
		this.monthlyAmount = monthlyAmount;
	}

	public Money getAmount() {
		return amount;
	}

	public void setAmount(Money amount) {
		this.amount = amount;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public String[] getTransactionOptions() {
		return TRANSACTION_OPTIONS;
	}

	@Override
	public String toString() {
		return "EventModel [month=" + month + ", interestRate=" + interestRate + ", monthlyAmount=" + monthlyAmount
				+ ", amount=" + amount + ", transactionType=" + transactionType + "]";
	}
}

src/main/java/com/psybergate/finance/controller/ForecastController.java
package com.psybergate.finance.controller;

import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.psybergate.finance.controller.dispatcher.PageDispatcher;
import com.psybergate.finance.domain.Record;
import com.psybergate.finance.interfaces.ForecastInfoViewModel;
import com.psybergate.finance.interfaces.ForecastService;
import com.psybergate.finance.resource.entity.PropertyBondRecord;

@ApplicationScoped
@Named
public class ForecastController {

	@Inject
	private ForecastInfoViewModel forecastInfoViewModel;

	@Inject
	private ForecastService forecastService;

	@Inject
	private InvestmentController investmentController;

	@Inject
	private PropertyBondController propertyBondController;

	private PageDispatcher pageDispatcher = new PageDispatcher();

	public List<Record> getListOfForecasts() {
		int customerNum = forecastInfoViewModel.getCustomerNum();
		return forecastService.listAvailableForecasts(customerNum);
	}

	public String generateForecast(Record record) {
		String nextPage = "";
		if (record.getRecordType().equals(Record.INVESTMENT_RECORD)) {
//			investmentController.generateForecast((InvestmentRecord) record);
			nextPage = "investmentForecast";
		} else if (record.getRecordType().equals(Record.BOND_RECORD)) {
//			propertyBondController.generateForecast((PropertyBondRecord) record);
			nextPage = "propertyBondForecast";
		}

		return pageDispatcher.getPage(nextPage);
	}
}

src/main/java/com/psybergate/finance/controller/PropertyBondController.java
package com.psybergate.finance.controller;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.spi.CDI;
import javax.inject.Inject;
import javax.inject.Named;

import com.psybergate.finance.controller.dispatcher.PageDispatcher;
import com.psybergate.finance.controller.validator.PropertyBondEventValidator;
import com.psybergate.finance.domain.Customer;
import com.psybergate.finance.domain.Event;
import com.psybergate.finance.domain.Money;
import com.psybergate.finance.domain.PropertyBond;
import com.psybergate.finance.exception.ApplicationException;
import com.psybergate.finance.interfaces.CustomerService;
import com.psybergate.finance.interfaces.PropertyBondService;
import com.psybergate.finance.model.CustomerViewModel;
import com.psybergate.finance.model.EventModel;
import com.psybergate.finance.model.PropertyBondData;
import com.psybergate.finance.model.PropertyBondViewModel;
import com.psybergate.finance.resource.entity.PropertyBondRecord;
import com.psybergate.finance.view.model.PropertyBondRecordViewModel;
import com.psybergate.web.view.forecast.propertybond.PropertyBondLineVisualisation;

@ApplicationScoped
@Named
public class PropertyBondController {

	@Inject
	private CustomerViewModel customerViewModel;

	@Inject
	private PropertyBondViewModel propertyBondViewModel;

	@Inject
	private PropertyBondService propertyBondService;

	@Inject
	private PropertyBondData propertyBondData;

	@Inject
	private CustomerService customerService;

	private PageDispatcher pageDispatcher = new PageDispatcher();

	@Inject
	private EventModel eventModel;

	public void generateForecast() {
		PropertyBond propertyBond = getPropertyBond();
		propertyBondViewModel.setForecast(propertyBond.getForecast());
		propertyBondViewModel.setPrincipal(propertyBond.getPrincipal());
		propertyBondViewModel.setConveyanceFees(propertyBond.getConveyanceFees());
		propertyBondViewModel.setConveyanceVatFees(propertyBond.getConveyanceVatFees());
		propertyBondViewModel.setTransferDutyFees(propertyBond.getTransferDutyFees());
		propertyBondViewModel.setTotalInterest(propertyBond.getTotalInterest());
		propertyBondViewModel.setTotalRepayment(propertyBond.getTotalRepayment());
	}

	public String generateForecastFromRecord(PropertyBondRecordViewModel propertyBondRecordViewModel) {
		System.out.println("=============");
		Money principal = new Money(propertyBondRecordViewModel.getPrincipal());
		Double interestRate = propertyBondRecordViewModel.getInterestRate();
		Integer term = propertyBondRecordViewModel.getTerm();
		Map<Integer, Event> events = propertyBondService.getPropertyBondEvents(propertyBondRecordViewModel.getId());

		propertyBondData.setPrincipal(principal);
		propertyBondData.setInterestRate(interestRate);
		propertyBondData.setTerm(term);
		propertyBondData.setEvents(events);

		System.out.println("######### " + propertyBondData);
		getPropertyBond();
		return pageDispatcher.getPage("propertyBondForecast");
	}

	public PropertyBond getPropertyBond() {
		PropertyBond propertyBond;
		try {
			PropertyBondEventValidator validator = new PropertyBondEventValidator();
			validator.validatePropertyBondData(propertyBondData);
			propertyBond = propertyBondService.generatePopertyBond(propertyBondData);
		}
		catch (ApplicationException e) {
			final Integer term = propertyBondViewModel.getTerm();
			Double interestRate = propertyBondViewModel.getInterestRate();
			Money principal = propertyBondViewModel.getPrincipal();
			Map<Integer, Event> events = propertyBondViewModel.getEvents();
			propertyBond = new PropertyBond(term, interestRate, principal, events);
		}
		return propertyBond;
	}

	public Event getEvent(EventModel eventModel) {
		Integer month = eventModel.getMonth();
		Double interestRate = eventModel.getInterestRate();
		Money amount = eventModel.getAmount();
		Money monthlyAmount = eventModel.getMonthlyAmount();
		String transactionType = eventModel.getTransactionType();
		if (amount != null && transactionType != null && transactionType.equalsIgnoreCase("withdraw")) {
			amount = new Money(amount.getAmount().negate());
		}
		return new Event(month, interestRate, amount, monthlyAmount);
	}

	public String generateForecast(PropertyBondRecord propertyBondRecord) {
		Double interestRate = propertyBondRecord.getInterestRate();
		String principal = propertyBondRecord.getPrincipal();
		Integer term = propertyBondRecord.getTerm();
		Map<Integer, Event> events = propertyBondService.getPropertyBondEvents(propertyBondRecord.getId());

		propertyBondData.setInterestRate(interestRate);
		propertyBondData.setPrincipal(new Money(principal));
		propertyBondData.setTerm(term);
		propertyBondData.setEvents(events);

		return pageDispatcher.getPage("propertyBondForecast");
	}

	public void addEvent() {
		Event event = eventModel.getEvent();
		try {
			PropertyBondEventValidator validator = CDI.current().select(PropertyBondEventValidator.class).get();
			validator.validateEvent(event);
			propertyBondViewModel.addEvent(event);
		}
		catch (Exception e) {}
	}

	public String savePropertyBond() {
		String customerName = customerViewModel.getName();
		Integer customerNum = customerViewModel.getCustomerNum();
		String propertyBondName = propertyBondViewModel.getPropertyBondName();
		BigDecimal principal = propertyBondViewModel.getPrincipal().getAmount();
		Integer term = propertyBondViewModel.getTerm();
		Double interestRate = propertyBondViewModel.getInterestRate();
		Map<Integer, Event> events = propertyBondViewModel.getEvents();

		Customer customer = new Customer(customerNum, customerName);
		customerService.saveCustomer(customer);
		propertyBondService.savePropertyBond(customer, propertyBondName, principal, term, interestRate, events);

		return pageDispatcher.getPage("propertyBondForecast");
	}

	public List<PropertyBondRecordViewModel> getListOfPropertyBonds() {
		System.out.println("Property Bond >>>>>>>>>>>>>>> customerViewModel: " + customerViewModel);

		Integer customerNum = customerViewModel.getCustomerNum();

		List<PropertyBondRecord> propertyBondRecords = propertyBondService.getSavedPropertyBondRecords(customerNum);

		List<PropertyBondRecordViewModel> records = new ArrayList<PropertyBondRecordViewModel>();
		for (PropertyBondRecord propertyBondRecord : propertyBondRecords) {
			// This id will be used to retrieve events.
			Integer id = propertyBondRecord.getId();
			String propertyBondName = propertyBondRecord.getPropertyBondName();
			String principal = propertyBondRecord.getPrincipal();
			Double interestRate = propertyBondRecord.getInterestRate();
			Integer term = propertyBondRecord.getTerm();

			PropertyBondRecordViewModel record =
					new PropertyBondRecordViewModel(id, customerNum, propertyBondName, principal, interestRate, term);
			records.add(record);
			System.out.println("Property Bond <<<<<<<<<<<<");
		}

		return records;
	}

	public static BigDecimal someMethod(PropertyBondViewModel propertyBondViewModel,
			PropertyBondLineVisualisation propertyBondLineVisualisation) {
		// PrintUtil.print("first param: " + propertyBondViewModel);
		// PrintUtil.print("second param: " + propertyBondLineVisualisation);
		// BigDecimal someValue = propertyBondViewModel.getTotalRepayment().getAmount()
		// .subtract(propertyBondViewModel.getTotalRepayment().getAmount().divide(
		// propertyBondLineVisualisation.getPrincipalTermAsBigDecimal(propertyBondViewModel),
		// 2,
		// RoundingMode.HALF_UP))
		// .divide(propertyBondViewModel.getTotalRepayment().getAmount().divide(
		// propertyBondLineVisualisation.getPrincipalTermAsBigDecimal(propertyBondViewModel),
		// 2,
		// RoundingMode.HALF_UP));
		// return someValue;
		return new BigDecimal(2500.05).setScale(2, BigDecimal.ROUND_CEILING);
	}

}

src/main/webapp/faces/dependencies/property-bond/forecast.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/WEB-INF/templates/finance-app-tmpl.xhtml">
	<ui:define name="title">propertyBond Forecast</ui:define>

	<ui:define name="content">
		#{propertyBondController.generateForecast()}
		<p:dialog header="Event" widgetVar="events-dialogue" minHeight="40"
			visible="#{!propertyBondEventValidator.valid}">

			<h:form id="propertyBondEventForm">
				<p:inputNumber id="event" rendered="false"></p:inputNumber>
				<p:message for="event" />
				<p:panelGrid columns="2">
					<b>Month: </b>
					<h:panelGroup>
						<div>
							<p:inputNumber id="month" value="#{eventModel.month}"
								minValue="0" decimalPlaces="0" />
							<p:message for="month" />
						</div>
					</h:panelGroup>

					<b>Change Monthly Repayment: </b>
					<h:panelGroup>
						<div>
							<p:inputNumber id="monthlyAmount"
								value="#{eventModel.monthlyAmount}">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyConverter" />
							</p:inputNumber>
							<p:message for="monthlyAmount" />
						</div>
					</h:panelGroup>
					<b>Change Interest Rate: </b>
					<h:panelGroup>
						<div>
							<p:inputNumber id="interestRate"
								value="#{eventModel.interestRate}" decimalPlaces="2"
								decimalSeparator="." />
							<p:message for="interestRate" />
						</div>
					</h:panelGroup>
					<b>Additional Transaction: </b>
					<h:panelGroup>
						<div>
							<p:selectOneMenu id="transactionType"
								value="#{eventModel.transactionType}">
								<f:selectItems value="#{eventModel.transactionOptions}" />
							</p:selectOneMenu>
							<p:inputNumber id="amount" value="#{eventModel.amount}"
								minValue="0">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyConverter" />
							</p:inputNumber>
							<p:message for="amount" />
						</div>
					</h:panelGroup>
				</p:panelGrid>
				<hr />
				<p:commandButton value="Add" ajax="false"
					action="#{propertyBondController.addEvent()}">
				</p:commandButton>
			</h:form>
		</p:dialog>

		<!-- Persistence -->
		<p:dialog header="Save Forecast" widgetVar="save-dialogue"
			minHeight="40" closeOnEscape="true">
			<h:form>
				<p:panelGrid columns="2">
					<b>Customer Number: </b>
					<h:panelGroup>
						<div>
							<p:inputNumber id="customerNum" minValue="0" decimalPlaces="0"
								placeholder="0" value="#{forecastInfo.customerNum}">
								<f:convertNumber type="number" groupingUsed="true"
									minFractionDigits="2" pattern="#0.00" />
							</p:inputNumber>
							<p:message id="saveCustomerNum" for="customerNum" />
						</div>
					</h:panelGroup>

					<b>Customer Name: </b>
					<h:panelGroup>
						<div>
							<p:inputText id="customerName"
								value="#{forecastInfo.customerName}" />
							<p:message id="saveCustomerName" for="customerName" />
						</div>
					</h:panelGroup>

					<b>Forecast Name: </b>
					<h:panelGroup>
						<div>
							<p:inputText id="forecastName"
								value="#{forecastInfo.forecastName}" />
							<p:message id="saveForecastName" for="forecastName" />
						</div>
					</h:panelGroup>

				</p:panelGrid>
				<hr />
				<p:commandButton value="Save Forecast"
					action="#{propertyBondController.savePropertyBond()}">
				</p:commandButton>
			</h:form>
		</p:dialog>

		<!-- Summary Content -->
		<p:tabView>

			<p:tab title="Forecast Table">
				<h:form>
					<!-- Table Content -->
					<p:dataTable id="forecast-table" var="entry"
						value="#{propertyBondViewModel.forecast}" scrollable="true"
						resizableColumns="true" scrollHeight="512"
						style="font-size:1.15em; border: 1pt solid #d4d4d4;">

						<f:facet name="header">

							<!-- Table Summary -->
							<p:panel header="Property Bond Summary" toggleable="true"
								collapsed="true" toggleSpeed="500" closeSpeed="500"
								widgetVar="summary-panel" style="border-style: none;">

								<!-- Summary Content -->
								<p:panelGrid style="width: 30em; margin: 0 auto;">
									<p:row>
										<p:column>
											<h:outputText value="Term" />
										</p:column>
										<p:column style="text-align: right;">
											<h:outputText value="#{propertyBondViewModel.term}" />
										</p:column>
									</p:row>

									<p:row>
										<p:column colspan="2"
											style="text-align: center; background-color: #f5f5f5;">
											<h:outputText value="Repayments (R)" />
										</p:column>
									</p:row>

									<p:row>
										<p:column style="text-align: left;">
											<h:outputText value="Principal" />
										</p:column>
										<p:column style="text-align: right;">
											<h:outputText value="#{propertyBondViewModel.principal}">
												<f:converter
													converterId="com.psybergate.web.converter.MoneyFormatter" />
											</h:outputText>
										</p:column>
									</p:row>

									<p:row>
										<p:column style="text-align: left;">
											<h:outputText value="Total Interest Amount" />
										</p:column>
										<p:column style="text-align: right;">
											<h:outputText value="#{propertyBondViewModel.totalInterest}">
												<f:converter
													converterId="com.psybergate.web.converter.MoneyFormatter" />
											</h:outputText>
										</p:column>
									</p:row>

									<p:row>
										<p:column style="text-align: left;">
											<h:outputText escape="false" value="Avg. Monthly Repayment" />
										</p:column>
										<p:column style="text-align: right;">
											<p:importConstants type="java.math.RoundingMode"
												var="RoundingMode" />
											<h:outputText
												value="#{propertyBondViewModel.totalRepayment.amount
															.divide(
																propertyBondLineVisualisation
																.getPrincipalTermAsBigDecimal(propertyBondViewModel),
																2,
																RoundingMode.HALF_UP	
															
															)
														}" />
										</p:column>
									</p:row>

									<p:row>
										<p:column style="text-align: left;">
											<h:outputText value="Total Repayment" />
										</p:column>
										<p:column style="text-align: right;">
											<h:outputText value="#{propertyBondViewModel.totalRepayment}">
												<f:converter
													converterId="com.psybergate.web.converter.MoneyFormatter" />
											</h:outputText>
										</p:column>
									</p:row>

								</p:panelGrid>

							</p:panel>

							<h:panelGroup style="display: block; text-align: left;">
								<p:commandButton id="add-event"
									onclick="PF('events-dialogue').show();" value="&#128197;Event"
									style="margin-left: 4px;" />
								<p:commandButton id="save-as-pdf" ajax="false"
									value="&#128190;PDF" style="margin-left: 4px;">
									<p:dataExporter type="pdf" target="forecast-table"
										fileName="property-bond-forecast" />
								</p:commandButton>
								<p:commandButton value="🌍Save" type="button"
									onclick="PF('save-dialogue').show();" style="margin-left: 4px;" />
							</h:panelGroup>
						</f:facet>

						<!-- Month -->
						<p:column headerText="Month" class="forecast-time-column">
							<h:outputText value="#{entry.month}"
								style="font-family: monospace;" />
						</p:column>

						<!-- Balance -->
						<p:column headerText="Opening Balance (R)"
							class="forecast-monetary-column">
							<h:outputText value="#{entry.openingBalance}"
								style="font-family: monospace;">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyFormatter" />
							</h:outputText>
						</p:column>

						<!-- Contribution -->
						<p:column headerText="Monthly Repayment (R)"
							class="forecast-monetary-column">
							<h:outputText value="#{entry.monthlyAmount}"
								style="font-family: monospace;">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyFormatter" />
							</h:outputText>
						</p:column>

						<!-- Deposit -->
						<p:column headerText="Deposit / Withdrawal (R)"
							class="forecast-monetary-column">
							<h:outputText value="#{entry.amount}"
								style="font-family: monospace;">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyFormatter" />
							</h:outputText>
						</p:column>

						<!-- Rate -->
						<p:column headerText="Interest Rate (%)"
							class="forecast-ration-column">
							<h:outputText value="#{entry.interestRate}"
								style="font-family: monospace;">
								<f:convertNumber type="number" groupingUsed="true"
									minFractionDigits="2" pattern="#0.00" />
							</h:outputText>
						</p:column>

						<!-- Interest -->
						<p:column headerText="Interest Amount (R)"
							class="forecast-monetary-column">
							<h:outputText value="#{entry.interest}"
								style="font-family: monospace;">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyFormatter" />
							</h:outputText>
						</p:column>

						<!-- Balance -->
						<p:column headerText="Closing Balance (R)"
							class="forecast-monetary-column">
							<h:outputText value="#{entry.closingBalance}"
								style="font-family: monospace;">
								<f:converter
									converterId="com.psybergate.web.converter.MoneyFormatter" />
							</h:outputText>
						</p:column>
					</p:dataTable>
				</h:form>

			</p:tab>

			<p:tab title="Forecast Graph">
				<p:chart type="line"
					model="#{propertyBondLineVisualisation.getModel(propertyBondViewModel)}"
					style="height:512px;" />
			</p:tab>

		</p:tabView>

	</ui:define>
</ui:composition>

</html>